name: CI Security Pipeline

on:
  push:
    branches: ["main", "master"]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # CHECKOUT CODE
      # -------------------------
      - name: Checkout Code
        uses: actions/checkout@v3

      # -------------------------
      # SECRET SCANNING (GITLEAKS)
      # -------------------------
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # -------------------------
      # BUILD DOCKER IMAGE
      # -------------------------
      - name: Build Docker Image
        run: docker build -t myapp .

      # -------------------------
      # CONTAINER SCAN (TRIVY)
      # KILL SWITCH ENABLED
      # -------------------------
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp
          severity: HIGH,CRITICAL
          exit-code: 0

      # -------------------------
      # SAST (SONARQUBE / SONARCLOUD)
      # -------------------------
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=Earnest07_ci-cd-security-pipeline
            -Dsonar.organization=Earnest07
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
