name: CI Security Pipeline

on:
  push:
    branches: ["main", "master"]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # CHECKOUT CODE
      # -------------------------
      - name: Checkout Code
        uses: actions/checkout@v3

      # -------------------------
      # SECRET SCANNING (GITLEAKS)
      # -------------------------
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # -------------------------
      # BUILD DOCKER IMAGE
      # -------------------------
      - name: Build Docker Image
        run: docker build -t myapp .

      # -------------------------
      # CONTAINER SCAN (TRIVY)
      # KILL SWITCH ENABLED
      # -------------------------
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp
          severity: HIGH,CRITICAL
          exit-code: 0

      # -------------------------
      # SAST (SONARQUBE / SONARCLOUD)
      # -------------------------
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=Earnest07_ci-cd-security-pipeline
            -Dsonar.organization=earnest07
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Debug scanner output
        run: |
          echo "Checking scannerwork..."
          ls -la .scannerwork || echo "No scannerwork found"
          cat .scannerwork/report-task.txt || echo "No report-task.txt"

      - name: Sonar Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
